### ISSUE TITLE
Validate Biobank ID's match with predefined format

### ISSUE THREAD

**Issue by esthervanenckevort** [BBMRI-ERIC/directory-scripts#1]
Collection ID matches with the following specification:

bbmri-eric:ID:\<CC\>_\<National ID\>

Where:
- \<CC\> is the ISO 3166-1 alpha-2 country code
- \<National ID\> is the ID of the biobank in the national directory
- The entire ID is constructed with only characters from the subset A-Z a-z 0-9 : _ -

**Comment by holubp** [comment]
Implemented in checks/ValidateIDs plugin
