### ISSUE TITLE
Check that policy allows collaborations with at least one group of users

### ISSUE THREAD

**Issue by esthervanenckevort** [BBMRI-ERIC/directory-scripts#13]
Check that the policy does not report false for both collaboration with non-profit and for-profit organisations.

**Comment by holubp** [comment]
This is actually only a heuristic check, since we don't have information directly about for-profit and non-for-profit, unless I am mistaken. How do you want to implement this?

**Comment by holubp** [comment]
Figured out. Check implemented in checks/BiobankFields plugin.
