### ISSUE TITLE
Validate collection ID's match with the predefined format

### ISSUE THREAD

**Issue by esthervanenckevort** [BBMRI-ERIC/directory-scripts#2]
Validate that the collection ID's match with the predefined format:

\<Biobank ID\>:collection:\<National ID\>

Where:
- \<Biobank ID\> is the ID of the biobank organization in the directory in the format bbmri-eric:ID_\<CC\>_\<National ID\>
- \<National ID\> is the ID in the National Directory
- Include validation that it matches with the biobank organization's ID
- The entire ID is constructed with only characters from the subset A-Z a-z 0-9 : _ -

**Comment by holubp** [comment]
Implemented in checks/ValidateIDs plugin

I am not sure what you meant with the "Include validation that it matches with the biobank organization's ID".
