### ISSUE TITLE
Validate that all contacts have an e-mail address

### ISSUE THREAD

**Issue by esthervanenckevort** [BBMRI-ERIC/directory-scripts#3]
Validate that all contacts have an e-mail address and that the address passes the smell test for a valid e-mail address.

**Comment by holubp** [comment]
Implemented in checks/ContactFields plugin. 

Testing of existence of the email address is currently turned off, as it required PyDNS and I am unable to install it on Cygwin for some reason. Also this test is pretty dramatic :-)
